# Generated by Django 5.2.4 on 2025-08-26 08:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_add_is_masked_field_to_link_trace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="link_role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commentator", "Commentator"),
                    ("editor", "Editor"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commentator", "Commentator"),
                    ("editor", "Editor"),
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentaskforaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commentator", "Commentator"),
                    ("editor", "Editor"),
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commentator", "Commentator"),
                    ("editor", "Editor"),
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="templateaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commentator", "Commentator"),
                    ("editor", "Editor"),
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "impress_comment",
                "ordering": ("-created_at",),
            },
        ),
    ]
